server:
  port : 8090
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        notify-input-stream-topic:
          destination: notify
          contentType: application/json
        notify-output-stream-topic:
          destination: notify
          contentType: application/json
